### ISSUE TITLE
Unable to update the value by changing the `true` attribute.

### ISSUE THREAD

**Issue by matthewp** [matthewp/if-else#1]

**Comment by matthewp** [comment]
This is really weird, my observedAttributes getter is never being called...

**Comment by Westbrook** [comment]
I think it’s this misspelling `observedAttribute`. I’m pretty sure it should be plural.

**Comment by matthewp** [comment]
@Westbrook I mispelled both that and `attributeChangedCallback` 👨 . Turns out if you don't have a `attributeChangedCallback` then `observedAttributes` is never called, that got me stuck for a minute...

**Comment by matthewp** [comment]
Ok, published in 1.0.1, thanks for the catch.
